NameThatFace/ViewModels/QuestionViewModel.cs
namespace NameThatFace.ViewModels
{
    public class QuestionViewModel
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Answer { get; set; }
    }
}

NameThatFace/ViewModels/ResultsViewModel.cs
using NameThatFace.Quiz;

namespace NameThatFace.ViewModels
{
    public class ResultsViewModel
    {
        public QuizInfo QuizInfo { get; set; }
        public int CorrectCount { get; set; }
        public int AnsweredCount { get; set; }
    }
}

NameThatFace/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NameThatFace.Controllers
{
    public class QuizController : Controller
    {
        //
        // GET: /Quiz/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New(string difficulty = "hard")
        {
            switch(difficulty)
            {
                case "easy":
                    return new RedirectResult("~/Quiz/Easy/Index");
                default:
                    return new RedirectResult("~/Quiz/Hard/Index");
            }
        }

    }
}

NameThatFace/Controllers/QuizHardController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using NameThatFace.Quiz;
using NameThatFace.ViewModels;

namespace NameThatFace.Controllers
{
    public class QuizHardController : Controller
    {
        //
        // GET: /Quiz/

        private QuizInfo CurrentQuiz
        {
            get { return QuizManager.GetCurrentQuiz(HttpContext.Session); }
        }

        public ActionResult Index()
        {
            if (QuizManager.IsCompleted(CurrentQuiz))
            {
                return new RedirectResult("Results/");
            }

            var lastAnswered = 0;
            var answers = (from o in CurrentQuiz.PastAnswers select o);
            var pos = 0;
            for (var i = 0; pos == 0 && i < answers.Count() - 1; i++)
            {
                var answer = answers.ElementAt(i);
                if (!string.IsNullOrWhiteSpace(answer.Answer))
                {
                    pos = i;
                }
            }

            return new RedirectResult("Question/" + (pos + 1));
        }
        
        public RedirectResult New()
        {
            QuizManager.ResetQuiz(HttpContext.Session);
            return new RedirectResult("Question/1");
        }

        public ActionResult Question(int id)
        {
            // human numbering (starts at 1)
            id = id - 1;

            var username = (from o in CurrentQuiz.Questions select o.Key).ElementAt(id);
            var model = new QuestionViewModel { Id = id, Username = username };
            return View(model);
        }

        public class AnswerRequestModel
        {
            [Required]
            public int Id { get; set; }

            [Required]
            public double Start { get; set; }

            [Required]
            public double Finish { get; set; }

            [Required]
            [MinLength(1), MaxLength(255)]
            public string Answer { get; set; }
        }

        public ActionResult Answer(AnswerRequestModel requestModel)
        {
            if (ModelState.IsValid == false)
            {
                var username = (from o in CurrentQuiz.Questions select o.Key).ElementAt(requestModel.Id - 1);
                var model = new QuestionViewModel { Id = requestModel.Id - 1, Username = username };
                return View("Question", model);
            }

            var correctUsername = (from o in CurrentQuiz.Questions select o.Key).ElementAt(requestModel.Id - 1);
            var begin = new DateTime(1970, 1, 1).AddMilliseconds(requestModel.Start);
            var end = new DateTime(1970, 1, 1).AddMilliseconds(requestModel.Finish);

            var timeTakenMs = end.Subtract(begin).TotalMilliseconds;

            QuizManager.AddAnswer(CurrentQuiz, correctUsername, requestModel.Answer, timeTakenMs);

            if (QuizManager.IsCompleted(CurrentQuiz))
            {
                return new RedirectResult("Results");
            }

            var newQuestionId = requestModel.Id + 1;
            return new RedirectResult("Question/" + newQuestionId);

        }

        public ActionResult Results()
        {
            var correctAnswers = 0;
            var usernamesLowercase = (from o in CurrentQuiz.Questions select o.Key.ToLower());
            foreach (string element in usernamesLowercase)
            {
                var matchingAnswers = (from o in CurrentQuiz.PastAnswers where o.CorrectUsername.ToLower() == element select o);
                if (matchingAnswers.Count() > 0 && matchingAnswers.First().Answer.ToLower() == matchingAnswers.First().CorrectFullName.ToLower())
                { 
                    correctAnswers++;
                }
            }

            var model = new ResultsViewModel
                            {
                                AnsweredCount = CurrentQuiz.PastAnswers.Count,
                                CorrectCount = correctAnswers,
                                QuizInfo = CurrentQuiz
                            };

            return View(model);
        }

    }
}

NameThatFace/Views/QuizHard/Question.cshtml
@model NameThatFace.ViewModels.QuestionViewModel
@{
    ViewBag.Title = "Question " + Model.Id;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="question">
    <h2>
        Who is this?</h2>
    <div class="question-face-holder">
        <img src="~/Faces/@(Model.Username).jpg"/>
        @{
            using (Html.BeginForm("Answer", "Quiz/Hard", FormMethod.Get, new { @class = "form-horizontal submit-answer" }))
            {
            @Html.Hidden("id", Model.Id)
            @Html.Hidden("start",  DateTime.Now.Subtract(new DateTime(1970, 1, 1)).TotalMilliseconds);
            @Html.Hidden("finish", "");
            <div class="control-group">
                <label class="control-label" for="inputAnswer">
                    This person is called:</label>
                <div class="controls">
                    <input type="text" class="answer" name="answer" id="answer" placeholder="Answer" />
                    @Html.ValidationMessageFor(o => o.Answer)
                </div>
            </div>   
            <div class="control-group">
                <div class="controls">
                    <button type="submit" onclick="submitForm" class="btn">
                        Answer</button>
                </div>
            </div>
            }
        }
        
        <script type="text/javascript">

            $(document).ready(function () {
                
                $("input.answer:first").focus();

                $("form.submit-answer").submit(function () {
                    var ms = (new Date).getTime();
                    $("input#finish").val(ms);
                });

            });

        </script>

    </div>
</div>

NameThatFace/Views/QuizHard/Results.cshtml
@using NameThatFace.Quiz
@model NameThatFace.ViewModels.ResultsViewModel
@{
    ViewBag.Title = "Results";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>
    Results</h2>
</p>
<h3>
    You scored @Model.CorrectCount out of @Model.QuizInfo.Questions.Count</h3>
<p>
    @Html.ActionLink("Start New Quiz", "New", "Quiz")
    <table class="quiz-results">
        <thead>
            <tr>
                <th>
                    Question #
                </th>
                <th>
                    Picture
                </th>
                <th>
                    Their name
                </th>
                <th>
                    Your answer
                </th>
                <th>
                    Result
                </th>
                <th>
                    Letters incorrect
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                for (int i = 0; i < Model.QuizInfo.Questions.Count; i++)
                {
                    var question = Model.QuizInfo.Questions.ElementAt(i);
                    var answers = (from o in Model.QuizInfo.PastAnswers where o.CorrectUsername.ToLower() == question.Key.ToLower() select o);
                    var answer = answers.Count() > 0 ? answers.First().Answer : "";
                    var distance = question.Value.PercentSimilar(answer);
                <tr>
                    <td>
                        @(i)
                    </td>
                    <td>
                        <img width="150" src="~/Faces/@(question.Key).jpg" alt="@(question.Value)"/>
                    </td>
                    <td>
                        @(question.Value)
                    </td>
                    <td>
                        @(answer)
                    </td>
                    @{
                    if (distance == 0)
                    {
                        <td class="result-correct result">
                            Correct!
                        </td>
                    }
                    else if (distance < QuizManager.DistanceDifficulty)
                    {
                        <td class="result-nearly-correct result">
                            Almost correct
                        </td>
                    }
                    else
                    {
                        <td class="result-wrong result">
                            Wrong
                        </td>
                    }}
                    <td>
                        @distance
                    </td>
                </tr>
                }
            }
        </tbody>
    </table>